### ISSUE TITLE
Question about your rasterizer details.

### ISSUE THREAD

**Issue by Mobiuslqm** [Zerg-Overmind/diff-gaussian-rasterization#3]
Hi, Thank you for sharing your codes. 
In your Readme.md , you mentioned that ` weight_per_gs_pixel are weights of top-K Gaussians per pixe` , but in your cuda implementation. [https://github.com/Zerg-Overmind/diff-gaussian-rasterization/blob/d5f00e7d8a4757a06595805259323b9924383ac6/cuda_rasterizer/forward.cu#L389](url)  it seems that  what you return   is  the cumulative wetight instead of weight per gaussian.   And in your paper,   you normalize the weights by dividing their sums.  Is this a bug or  i misunderstood your meaning?
![Weixin Screenshot_20240422185020](https://github.com/Zerg-Overmind/diff-gaussian-rasterization/assets/64359313/30dfa886-9775-467b-bee8-2c1247ba1a33)
Regards.

**Comment by Zerg-Overmind** [comment]
Hi, thanks for the interest.
According to rendering equation C=\sum \alpha_i * T_i * c_i, the weight of each Gaussian is w_i=\alpha_i * T_1, which means the weight term consists of an independent weight \alpha per Gaussian and a cumulative weight T_1.
Also, normalizing the sum is not a bug. Because we want the sum of these top-K Gaussians' flow (instead of all Gaussians) to be equal to optical value of each pixel. Usaully, Gaussians other than top-k have small weights but we cannot ignore so we use normalization to exclude them.

**Comment by Mobiuslqm** [comment]
Thank you for your prompt reply. I understand the reason why you nomalizing it.
But  what  i am confused about is the cumulative is T_t = T_t-1*(1-alpha_t-1),  not sum.  in your code. the element of  weights returned  will be  more and more close to 1 when the index is close  K.   
![image](https://github.com/Zerg-Overmind/diff-gaussian-rasterization/assets/64359313/57ab7969-1f32-433e-9af1-7b4e5267f5ea)

**Comment by Zerg-Overmind** [comment]
Oops, I got what you saying. It should be alpha*T instead of weight. Somehow I uploaded the code for internal test and ablations... I shall fix it ASAP. 
Thanks!

**Comment by Mobiuslqm** [comment]
By the way, could  you please share the  pytorch-part codes of integrating the flow of differennt gaussians? My implementation met some bugs, It doesn't work.  Thanks very much!!

**Comment by Zerg-Overmind** [comment]
Hi, I've just replied your email !
